[constants]
    machine="Machine_1"	#Name of the machine being monitored (can't have spaces)

[threshold]
    th1 = 50  #for 1 sensor

[sensing]
    # uncomment (remove the leading #) from the sensor that you are using:

    # Contact temperature sensors:
    adc = "W1ThermSensor"   # Always connect the DS18B20 sensor to GPIO4 (physical pin 7) of the RPi4
    #adc = "PT100_arduino"
    #adc = "PT100_raspi_MAX31865"
    #adc = "PT100_raspi_SMHAT"
    #adc = "K-type_DFRobot_MAX31855"

    # Air temperature sensors:
    #adc = "AHT20"
    #adc = "SHT30"

    # Infrared temperature sensors:
    #adc = "MLX90614"

[sampling]
    sample_count = 1
    sample_interval = 1

[computing]
    hardware="Pi4"

[mqtt]
    broker = "mqtt.docker.local"
    port = 1883   #common mqtt ports are 1883 and 8883
    base_topic_template = "temperature_monitoring/{{machine}}"

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds
